### ISSUE TITLE
Error initializing new project

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/VFPXDeployment#31] opened 2023-07-21 14:34 UTC
## ℹ Computer information

- VFP version: 9.0 SP 2
- VFPX Deployment version: 1.4

## 📝 Provide detailed reproduction steps (if any)

Installing new project

### ❌ Actual result

This error:

## 📷 Screenshots

![image](https://github.com/VFPX/VFPXDeployment/assets/81179335/72122bfe-532f-43aa-91ad-34e1865a58ef)

**Comment by DougHennig** [comment] 2023-07-30 14:17
This seems to be fixed in the latest version (I can't reproduce it).

**Closed by DougHennig** 2023-07-30 14:17 UTC
